name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-iotdb-win-cpp:
    runs-on: windows-latest
    env:
      BOOST_PATH: ${{github.workspace}}

    steps:
      - name: set-java
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: 8
        run: java -version

      - name: get-cmake
        uses: lukka/get-cmake@v3.23.0
        run: cmake --help

      - name: install boost
        uses: MarkusJx/install-boost@v2.1.0
        id: install-boost
        with:
          boost_version: 1.78.0
          platform_version: 2019
          toolset: msvc
          boost_install_dir: ${{ env.BOOST_PATH }}
        run: |
          dir

#      - name: install FileDownloader
#        run: |
#          dotnet tool install -g dotnetCampus.FileDownloader.Tool

      - name: down flex&bison
        run: |
#          DownloadFile -u https://jaist.dl.sourceforge.net/project/winflexbison/win_flex_bison-latest.zip -o win_flex_bison-latest.zip
          wget https://jaist.dl.sourceforge.net/project/winflexbison/win_flex_bison-latest.zip 
          dir

        
