name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-iotdb-win-cpp:
    runs-on: windows-2022

    steps:
      - name: install boost
        uses: MarkusJx/install-boost@v2.1.0
        id: install-boost
        with:
          boost_version: 1.78.0
          platform_version: 2022
          toolset: msvc
          boost_install_dir: ${{ github.workspace }}

      - name: download flex&bison
        run: |
          C:\msys64\usr\bin\wget.exe -O ${{ github.workspace }}/win_flex_bison-latest.zip https://jaist.dl.sourceforge.net/project/winflexbison/win_flex_bison-latest.zip
          7z x win_flex_bison-latest.zip -owin_flex_bison-latest

      - name: Checkout apache/iotdb
        uses: actions/checkout@v2
        with:
          path: iotdb
          repository: 'apache/iotdb'
          ref: rel/0.13
          fetch-depth: 0

      - name: compile client-cpp
        shell: cmd
        run: |
          cd ${{ github.workspace }}\iotdb
          set Path=%Path%;${{ github.workspace }}\win_flex_bison-latest
          set Path
          mvn package -Dcmake.generator="Visual Studio 17 2022" -P compile-cpp -pl client-cpp,server,example/client-cpp-example -am -DskipTests -Dboost.include.dir="${{ github.workspace }}\boost\boost" -Dboost.library.dir="${{ github.workspace }}\boost\boost\stage\lib"
