name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-iotdb-win-cpp:
    runs-on: windows-latest

    steps:
      - name: set-java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8

      - name: get-cmake
        uses: lukka/get-cmake@v3.23.0

      - name: cmake-help
        run: cmake --help

      - name: install boost
        uses: MarkusJx/install-boost@v2.1.0
        id: install-boost
        with:
          boost_version: 1.78.0
          platform_version: 2019
          toolset: msvc
          boost_install_dir: ${{ github.workspace }}

      - name: set boost path
        id: set-boost
        run: |
          echo "::set-output name=include-dir::echo ${{ env.BOOST_PATH }}/boost/boost"
          echo "::set-output name=library-dir::echo ${{ env.BOOST_PATH }}/boost/boost/stage/lib"

      - name: echo boost path
        run: |
          echo ${{ steps.set-boost.outputs.include-dir }}
          dir ${{ steps.set-boost.outputs.include-dir }}
          echo ${{ steps.set-boost.outputs.library-dir }}
          dir ${{ steps.set-boost.outputs.library-dir }}

      - name: install FileDownloader
        run: |
          dotnet tool install -g dotnetCampus.FileDownloader.Tool

      - name: down flex&bison
        run: |
          DownloadFile -u https://jaist.dl.sourceforge.net/project/winflexbison/win_flex_bison-latest.zip -o win_flex_bison-latest.zip
          dir

        
