name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-iotdb-win-cpp:
    runs-on: windows-latest

    steps:
#      - name: install boost
#        uses: MarkusJx/install-boost@v2.1.0
#        id: install-boost
#        with:
#          boost_version: 1.78.0
#          platform_version: 2019
#          toolset: msvc
#          boost_install_dir: ${{ github.workspace }}
#
#      - name: set boost path
#        id: set-boost
#        run: |
#          echo "::set-output name=include-dir::${{ github.workspace }}/boost/boost"
#          echo "::set-output name=library-dir::${{ github.workspace }}/boost/boost/stage/lib"
#
#      - name: echo boost path
#        run: |
#          echo ${{ steps.set-boost.outputs.include-dir }}
#          echo ${{ steps.set-boost.outputs.library-dir }}

      - name: download flex&bison
        run: |
          C:\msys64\usr\bin\wget.exe -O ${{ github.workspace }}/win_flex_bison-latest.zip https://jaist.dl.sourceforge.net/project/winflexbison/win_flex_bison-latest.zip
          7z x win_flex_bison-latest.zip
          dir
          
        
