name: test
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-client-cpp-win:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        os: [ windows-2019,windows-2022 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: run cmake help
        run: |
          cmake --help